# Generated by Django 3.1.5 on 2021-01-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('znak', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Xyz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('X', models.TextField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.PositiveBigIntegerField()),
                ('name', models.TextField()),
                ('quantity', models.FloatField()),
                ('ediz', models.TextField()),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
                ('mol', models.TextField()),
                ('groups_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Positions.groups')),
                ('xyz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Positions.xyz')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Positions.levels')),
            ],
        ),
        migrations.CreateModel(
            name='Change_qantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_oper', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('change_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Positions.change_types')),
                ('object_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Positions.objects')),
                ('person_id_contr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contr', to='Positions.persons')),
                ('person_id_mol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mol', to='Positions.persons')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Positions.positions')),
            ],
        ),
    ]
