# Generated by Django 3.1.1 on 2021-03-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
