# Generated by Django 3.1.1 on 2021-03-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Positions', '0002_dokuments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dokuments',
            new_name='Documents',
        ),
    ]
